version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: newsletters         # Nom de la base de données
      POSTGRES_USER: yns               # Nom de l'utilisateur
      POSTGRES_PASSWORD: yns           # Mot de passe de l'utilisateur
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - django_network
    ports:
      - "5432:5432"                    # Expose le port PostgreSQL pour les connexions externes (facultatif)
    restart: unless-stopped            # Redémarre automatiquement sauf si le conteneur est arrêté manuellement

  web:
    build:
      context: .  # Le chemin où se trouve votre Dockerfile
    container_name: django_app
    command: gunicorn --bind 0.0.0.0:8000 --access-logfile - --error-logfile - newsletter_project.wsgi:application
    volumes:
      - .:/app  # Monte le répertoire du projet local sur le conteneur
      - ./static:/app/staticfiles  # Monte le répertoire des fichiers statiques
    ports:
      - "8000:8000"   # Expose le port Django sur la machine hôte
    depends_on:
      - db  # Assure que la base de données démarre avant l'application Django
    environment:
      DEBUG: '0'  # Désactive le mode debug pour la production
      SECRET_KEY: "django-insecure-f=f_4xs8rt%=vctzcr39z%(08f+@nc^q+lb*ncar5qbuwqlo=2"  # Remplacez par votre clé secrète Django
      POSTGRES_DB: newsletters
      POSTGRES_USER: yns
      POSTGRES_PASSWORD: yns
      DATABASE_URL: "postgres://yns:yns@db:5432/newsletters"
    networks:
      - django_network
    restart: unless-stopped  # Redémarre automatiquement sauf si le conteneur est arrêté manuellement

volumes:
  postgres_data:

networks:
  django_network:
    driver: bridge
