# Generated by Django 4.0 on 2024-10-23 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=50)),
                ('localisation', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=10)),
                ('news_type', models.CharField(choices=[('price_trends', 'Tendances des prix'), ('mortgages', 'Crédits immobiliers'), ('sales_purchases', 'Ventes et achats'), ('housing_availability', 'Disponibilité du logement'), ('interest_rate_impact', 'Impact des taux d’intérêt'), ('innovation_technology', 'Innovation et technologie'), ('demographic_trends', 'Tendances démographiques')], max_length=50)),
                ('impact_real_estate', models.BooleanField(default=False)),
                ('impact_technology', models.BooleanField(default=False)),
                ('impact_finance', models.BooleanField(default=False)),
                ('impact_construction', models.BooleanField(default=False)),
                ('impact_retail', models.BooleanField(default=False)),
                ('impact_transport_logistics', models.BooleanField(default=False)),
                ('impact_education', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.IntegerField(default=10)),
                ('total_newsletters_created', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lien_img', models.URLField(blank=True, default='https://images.pexels.com/photos/2695680/pexels-photo-2695680.jpeg', max_length=500, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
                ('news', models.ManyToManyField(to='newsletters.News')),
            ],
        ),
    ]
